sudo: false
language: node_js
before_install:
  - nvm install stable
script:
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/master/cla-travis.sh | bash
  - npm run build
  - if git update-index -q --refresh && ! git diff-index --quiet HEAD; then echo repo is dirty; exit 1; fi
  - nvm install $TRAVIS_NODE_VERSION
  - npm test
  - npm run lint
node_js:
  - "6"
  - "8"
  - "10"
